# Copyright (c) 2021 Carsten Rudolph
name: Verify Build

on:
  workflow_dispatch:
    inputs:
      uploadArtifacts:
        description: 'Upload Artifacts'
        required: true
        default: 'false'
      signArtifacts:
        description: 'Attempt Code Sign'
        required: true
        default: 'false'
        
  pull_request:
    branches:
      - main
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

env:
  vulkanSdkVersion: '1.2.148.0' # Lowest version that ships with DXC is 1.2.148.0

jobs:
  job:
    name: ${{ matrix.os }}-ci
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' || !github.event.pull_request.draft }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            configuration: windows-x64-release
            architecture: x64

    steps:
      - name: Checking out sources
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup build environment
        id: setup-environment
        run: |
          echo "VCPKG_FEATURE_FLAGS=manifests" >> $env:GITHUB_ENV
          $vulkanDir = "C:\VulkanSDK\${{ env.vulkanSdkVersion }}"
          echo "Installing Vulkan SDK to: $($vulkanDir)..."
          echo "VULKAN_SDK=$($vulkanDir)" >> $env:GITHUB_ENV
          New-Item -ItemType directory -Path $vulkanDir

      - name: Setup Vulkan SDK cache
        id: vulkan-sdk-cache
        uses: actions/cache@v3
        with:
          path: ${{ env.VULKAN_SDK }}
          key: VulkanSDK-${{ env.vulkanSdkVersion }}-Windows

      - name: Setup Vulkan SDK
        if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
        run: | 
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.vulkanSdkVersion }}/windows/VulkanSDK-$${{ env.vulkanSdkVersion }}-Installer.exe" -OutFile VulkanSDK.exe           
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");           
          $installer.WaitForExit();

      - name: Retrieve latest CMake build
        uses: lukka/get-cmake@latest

      - name: Restore or build vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/src/Modules/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Build with CMake and Ninja
        id: build-with-cmake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
          configurePreset: '${{ matrix.configuration }}'
          buildPreset: '${{ matrix.configuration }}'
          
      - name: Install with CMake
        run: |
          Set-Location '${{ github.workspace }}/out/build/${{ matrix.configuration }}'
          cmake --install .
          
      - name: Sign binaries
        if: ${{ github.event.inputs.signArtifacts == 'true' }}
        uses: dlemstra/code-sign-action@v1
        with:
          certificate: '${{ secrets.SIGN_CERTIFICATE_BASE64 }}'
          password: '${{ secrets.SIGN_CERTIFICATE_PASSWORD }}'
          folder: '${{ github.workspace }}/out/install/'
          recursive: true

      - name: Upload install artifacts
        if: ${{ github.event.inputs.uploadArtifacts == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: LiteFX-${{ matrix.triplet }}-install
          path: '${{ github.workspace }}/out/install/${{ matrix.configuration }}'
