# Copyright (c) 2021 Carsten Rudolph
name: Publish Release

on:
  workflow_dispatch:
    inputs:
      major:
        description: 'Major Version'
        required: true
      minor:
        description: 'Minor Version'
        required: true
      build:
        description: 'Build Number'
        required: true
      Changelog:
        description: 'Change Log and Release Notes'
        required: true

env:
  vulkanSdkVersion: '1.2.148.0' # Lowest version that ships with DXC is 1.2.148.0

jobs:
  build:
    name: ${{ matrix.profile }}
    runs-on: windows-latest
    strategy:
      fail-fast: true
      matrix:
        profile: [ windows-x64, windows-x86 ]
        include:
          - profile: windows-x64
            triplet: x64-windows
            architecture: x64
          - profile: windows-x86
            triplet: x86-windows
            architecture: x86

    steps:
      - name: Checking out sources
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup build environment
        id: setup-environment
        run: |
          echo "VCPKG_FEATURE_FLAGS=manifests" >> $env:GITHUB_ENV
          $vulkanDir = "C:\VulkanSDK\${{ env.vulkanSdkVersion }}"
          echo "Installing Vulkan SDK to: $($vulkanDir)..."
          echo "VULKAN_SDK=$($vulkanDir)" >> $env:GITHUB_ENV
          $buildPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('${{ github.workspace }}/../out/build/')
          Write-Output "::set-output name=buildPath::$($buildPath)"
          $installPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('${{ github.workspace }}/../out/install/')
          Write-Output "::set-output name=installPath::$($installPath)"
          New-Item -ItemType directory -Path $vulkanDir

      - name: Setup Vulkan SDK cache
        id: vulkan-sdk-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.VULKAN_SDK }}
          key: VulkanSDK-${{ env.vulkanSdkVersion }}-Windows

      - name: Setup Vulkan SDK
        if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
        run: | 
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.vulkanSdkVersion }}/windows/VulkanSDK-$${{ env.vulkanSdkVersion }}-Installer.exe" -OutFile VulkanSDK.exe           
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");           
          $installer.WaitForExit();

      - name: Retrieve latest CMake build
        uses: lukka/get-cmake@latest

      - name: Restore or build vcpkg
        uses: lukka/run-vcpkg@v6
        with:
          setupOnly: true
          vcpkgDirectory: '${{ github.workspace }}/src/Modules/vcpkg'
          appendedCacheKey: ${{ hashFiles( '**/vcpkg.json' ) }}
          vcpkgTriplet: ${{ matrix.triplet }}
          additionalCachedPaths: ${{ steps.setup-environment.outputs.buildPath }}/vcpkg_installed

      - name: Build with CMake and Ninja (Debug)
        id: build-with-cmake-debug
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          cmakeSettingsJsonPath: '${{ github.workspace }}/src/CMakeSettings.json'
          configurationRegexFilter: '${{ matrix.architecture }}-Debug'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.architecture }}-Debug'

      - name: Install with CMake (Debug)
        run: |
          Set-Location '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.architecture }}-Debug'
          cmake --install .
          
      - name: Build with CMake and Ninja (Release)
        id: build-with-cmake-release
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          cmakeSettingsJsonPath: '${{ github.workspace }}/src/CMakeSettings.json'
          configurationRegexFilter: '${{ matrix.architecture }}-Release'
          useVcpkgToolchainFile: true
          buildDirectory: '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.architecture }}-Release'

      - name: Install with CMake (Release)
        run: |
          Set-Location '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.architecture }}-Release'
          cmake --install .

      - name: Upload install artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LiteFX-${{ matrix.triplet }}-install
          path: '${{ steps.setup-environment.outputs.buildPath }}/install'
          
  publish:
    name: 'Publish'
    needs: build
    runs-on: windows-latest
    strategy:
      fail-fast: true
      
    steps:
      - name: 'Download windows-x64 artifacts...'
        uses: actions/download-artifact@master
        with:
          name: LiteFX-windows-x64-install
          path: release/x64/
          
      - name: 'Download windows-x86 artifacts...'
        uses: actions/download-artifact@master
        with:
          name: LiteFX-windows-x86-install
          path: release/x86/