# Copyright (c) 2021 Carsten Rudolph
name: Weekly

on:
  workflow_dispatch:
    inputs:
      uploadBuildArtifacts:
        description: 'Upload Build Artifacts'
        required: true
        default: 'false'
        
  schedule: 
    - cron: '1 0 * * 1'         # Run every monday night at 00:01 AM (UTC).
    
env:
  vulkanSdkVersion: '1.2.148.0' # Lowest version that ships with DXC is 1.2.148.0

jobs:
  job:
    name: ${{ matrix.os }}-weekly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
            configuration: windows-x64-release
            architecture: x64

    steps:
      - name: Checking out sources
        uses: actions/checkout@master
        with:
          submodules: true

      - name: Setup build environment
        id: setup-environment
        run: |
          echo "VCPKG_FEATURE_FLAGS=manifests" >> $env:GITHUB_ENV
          $vulkanDir = "C:\VulkanSDK\${{ env.vulkanSdkVersion }}"
          echo "Installing Vulkan SDK to: $($vulkanDir)..."
          echo "VULKAN_SDK=$($vulkanDir)" >> $env:GITHUB_ENV
          $buildPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('${{ github.workspace }}/out/build/')
          Write-Output "::set-output name=buildPath::$($buildPath)"
          $installPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath('${{ github.workspace }}/out/install/')
          Write-Output "::set-output name=installPath::$($installPath)"
          New-Item -ItemType directory -Path $vulkanDir

      - name: Setup Vulkan SDK cache
        id: vulkan-sdk-cache
        uses: actions/cache@v2
        with:
          path: ${{ env.VULKAN_SDK }}
          key: VulkanSDK-${{ env.vulkanSdkVersion }}-Windows

      - name: Setup Vulkan SDK
        if: steps.vulkan-sdk-cache.outputs.cache-hit != 'true'
        run: | 
          Invoke-WebRequest -Uri "https://sdk.lunarg.com/sdk/download/${{ env.vulkanSdkVersion }}/windows/VulkanSDK-$${{ env.vulkanSdkVersion }}-Installer.exe" -OutFile VulkanSDK.exe           
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");           
          $installer.WaitForExit();

      - name: Retrieve latest CMake build
        uses: lukka/get-cmake@latest
        
      - name: Setup MSVC CLI
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Restore or build vcpkg
        uses: lukka/run-vcpkg@v10
        with:
          vcpkgDirectory: '${{ github.workspace }}/src/Modules/vcpkg'
          vcpkgJsonGlob: '**/vcpkg.json'

      - name: Build with CMake and Ninja
        id: build-with-cmake
        uses: lukka/run-cmake@v10
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/src/CMakeLists.txt'
          configurePreset: "${{ matrix.configuration }}"
          buildPreset: "release-${{ matrix.architecture }}"
          
      - name: Upload build artifacts
        if: ${{ github.event.inputs.uploadBuildArtifacts == 'true' }}
        uses: actions/upload-artifact@v2
        with:
          name: LiteFX-${{ matrix.triplet }}-build
          path: '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.configuration }}'
          
      - name: Install with CMake
        run: |
          Set-Location '${{ steps.setup-environment.outputs.buildPath }}/${{ matrix.configuration }}'
          cmake --install .

      - name: Upload install artifacts
        uses: actions/upload-artifact@v2
        with:
          name: LiteFX-${{ matrix.triplet }}-install
          path: '${{ steps.setup-environment.outputs.installPath }}'
