# Copyright (c) 2020 Carsten Rudolph
name: Weekly
on:
  workflow_dispatch
#  schedule:
#    - cron: '0 2 * * *'

jobs:
  job:
    name: ${{ matrix.os }}-Weekly
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest ]
        include:
          - os: windows-latest
            triplet: x64-windows
    steps:
      - name: Checking out sources
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Retrieve latest CMake build
        uses: lukka/get-cmake@latest

      - name: Restore or build vcpkg
        uses: lukka/run-vcpkg@v3
        id: runvcpkg
        with:
          setupOnly: true
          vcpkgGitCommitId: b79f7675aaa82eb6c5a96ae764fb1ce379a9d5d6 

      - name: Build with CMake and Ninja
        uses: lukka/run-cmake@v2
        with:
          cmakeListsOrSettingsJson: CMakeSettingsJson
          cmakeSettingsJsonPath: '${{ github.workspace }}/src/CMakeSettings.json'
          useVcpkgToolchainFile: true
          configurationRegexFilter: '${{ matrix.configuration }}'
